### ISSUE TITLE
setMaxResults produces invalid SQL

### ISSUE THREAD

**Issue by The-Canned-Moose** [exasol/hibernate-exasol#2]
When you use setMaxResult on the query, the resulting SQL seems to be invalid resulting in an SQLException.
This is a test for it:
`public class QueryTest extends HibernateTest {

	private Session session;
	private EntityManager manager;

	public QueryTest(){
		this.manager = super.getManager();
	}
	
	public void testLimit(){
		 List<String> res = manager.createQuery("FROM Event").setMaxResults(1).getResultList();
		 assertTrue(res.size()==1);
	}
}`
The result is:

> ERROR: non-negative integer value expected in LIMIT clause [line 1, column 285] (Session: 1584952501486566879)

**Comment by gdrt94** [comment]
Fixed in the pull request: https://github.com/exasol/hibernate-exasol/pull/3
